name: Test Flask with Secret
on: [push]
jobs:
  Test-Flask-With-Secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Unit tests
        run: |
          pytest -v
      - name: Test Flask with Secret
        shell: bash
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          FLASK_APP: main
        run: |
          cd easyboard
          gunicorn -b 127.0.0.1:5000 --daemon main:app
          sleep 1s
          curl "http://127.0.0.1:5000/api/distance?originLat=1.31&originLong=103.75&destinLat=1.32&destinLong=103.76"
      - run: echo "🍏 This job's status is ${{ job.status }}."
